# Generated by Django 3.0.1 on 2021-05-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('workclass', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('maritalstatus', models.CharField(max_length=50)),
                ('hoursofwork', models.CharField(max_length=50)),
                ('income', models.CharField(max_length=50)),
            ],
        ),
    ]
