# Generated by Django 3.0.1 on 2021-05-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('comment', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='profile1',
        ),
        migrations.RenameModel(
            old_name='Upload',
            new_name='upload1',
        ),
    ]
