# Generated by Django 3.0.1 on 2021-05-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_auto_20210505_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile1',
            new_name='Profile',
        ),
        migrations.RenameModel(
            old_name='upload1',
            new_name='Upload',
        ),
    ]
