# Generated by Django 3.0.1 on 2021-05-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('psw', models.TextField(max_length=200)),
                ('psw_repeat', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'registerdonor',
            },
        ),
    ]
