# Generated by Django 3.1.5 on 2021-05-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_auto_20210506_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='filepath',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
