# Generated by Django 3.1.5 on 2021-05-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0009_upload_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='filepath',
            field=models.ImageField(null=True, upload_to='img/', verbose_name=''),
        ),
    ]
