# Generated by Django 3.1.5 on 2021-05-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0010_auto_20210508_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='filepath',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
