# Generated by Django 3.0.1 on 2021-05-11 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0013_donorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='RegisterDonor',
        ),
    ]
